name: MacOS Intel

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: make
      run: MACOSX_DEPLOYMENT_TARGET=10.15 make
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: fpb-development-macos-11-x86_64
        path: FPB
